### ISSUE TITLE
[ImportError] - There is no 'INSTANCE_OFFSET' constant in 'mmdet.datasets.coco_panoptic' python file

### ISSUE THREAD

**Issue by synacktraa** [Jingkang50/OpenPSG#105]
```
ImportError: cannot import name 'INSTANCE_OFFSET' from 'mmdet.datasets.coco_panoptic' (/usr/local/lib/python3.10/dist-packages/mmdet/datasets/coco_panoptic.py)
```

![image](https://github.com/Jingkang50/OpenPSG/assets/91981716/8e364450-532e-4d34-b041-0e8f325bb238)

**Comment by brianbscho** [comment]
Probably your mmdet version isn't matching with the OpenPSG required one. You can find `INSTANCE_OFFSET` in below file.

https://github.com/open-mmlab/mmdetection/blob/2.x/mmdet/core/evaluation/panoptic_utils.py

`INSTANCE_OFFSET = 1000`
