### ISSUE TITLE
Where is the epoch_60.pth?

### ISSUE THREAD

**Issue by hiker-lw** [Jingkang50/OpenPSG#108]
thank you for your Interesting work. Can you tell me how to get the pretrained checkpoint?

**Comment by lrrry** [comment]
I'm currently working with the OpenPSG framework and noticed that the original PSG model zoo links (e.g., from OneDrive) are no longer accessible. I was wondering if you happen to have downloaded the various pretrained weights for the different models (e.g., PSGTR, PSGFormer, VCTree, etc.) before the links went offline?

If so, would it be possible for you to share them with me (via Google Drive, Dropbox, or any other means)? It would be a huge help for my research.
