### ISSUE TITLE
The datasets link has been removed ？

### ISSUE THREAD

**Issue by YuxiangZhang-BIT** [Jingkang50/OpenPSG#11]
Click Datasets to display "This link has been removed."
[https://entuedu-my.sharepoint.com/:f:/g/personal/jingkang001_e_ntu_edu_sg/EgQzvsYo3t9BpxgMZ6VHaEMBY9ZRx3XJzfPjo8uhw5Rv6Q?e=BLFFyb](url)

**Comment by Jingkang50** [comment]
Thank you for your interest in PSG! 
We are preparing a new link for PSG competition, where part of the validation set becomes private.
Will update very soon.

**Comment by Jingkang50** [comment]
Fixed! Please enjoy!

**Comment by Jingkang50** [comment]
Per request from the International Algorithm Case Competition committee, the PSG data should only be available from their official website. https://iacc.pazhoulab-huangpu.com/
