### ISSUE TITLE
是否考虑更新平台版本

### ISSUE THREAD

**Issue by nidongpinyinme** [Jingkang50/OpenPSG#112]
当前mmcv已经进行了大版本升级，并且弃用了很多接口，导致当前的平台不兼容新的mmcv和mmdet等模块。请问你们是否有适配计划？

**Comment by Jingkang50** [comment]
感谢对我们的工作的关注和建议！
我们近期（四个月内）应该没有计划更新。如果社区有其他团队有基于openpsg的更新计划，我们很乐意提供支持

**Comment by nidongpinyinme** [comment]
好的，谢谢。
