### ISSUE TITLE
submit function error:AttributeError: 'NoneType' object has no attribute 'astype'

### ISSUE THREAD

**Issue by ZHUXUHAN** [Jingkang50/OpenPSG#14]
when i test the model for submission, the code occour :
    relations=rels.astype(np.int32).tolist(),
AttributeError: 'NoneType' object has no attribute 'astype'

my scripts:
PYTHONPATH='.':$PYTHONPATH \
python tools/test.py \
     configs/psgformer/psgformer_r50_psg.py \
     /userhome/data/psg_weights/psgformer_r50/epoch_60.pth \
     --submit 
how can i solve this problem? thank you very much for your help.

**Comment by Jingkang50** [comment]
@GSeanCDAT Zujin, could you help check this problem?
@ZHUXUHAN Could you check the "--submit" for two-stage methods first? We might need some time to figure it out.

**Comment by ZHUXUHAN** [comment]
> @GSeanCDAT Zujin, could you help check this problem? @ZHUXUHAN Could you check the "--submit" for two-stage methods first? We might need some time to figure it out.

hi, i just test your provided  two-stage model of  vctree for submission. i don't meet the same problem, and i successfully get the submission results, but when i upload the result to the codalab sever, there occour a problem:

Traceback (most recent call last):
  File "/worker/worker.py", line 313, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 132, in get_bundle
    with ZipFile(bundle_file.file, 'r') as z:
  File "/usr/local/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file

I see the format of my submission.zip is the  same format of your suggestion. so i think you should just modify it. Othersie, i guess the provided demo of submission.zip is wrong, so you should just check it's format again.

**Comment by Jingkang50** [comment]
Congratulations on your success on getting the submission.zip.
The codalab server is down as the request from international algorithm case competition committee.
They will provide the ONLY / Exclusive protocol for the PSG competition.
We will update all the rules when everything is settled.
I believe there is no problem on your submission.

**Comment by ZHUXUHAN** [comment]
> Congratulations on your success on getting the submission.zip.
> The codalab server is down as the request from international algorithm case competition committee.
> They will provide the ONLY / Exclusive protocol for the PSG competition.
> We will update all the rules when everything is settled.
> I believe there is no problem on your submission if you are using --submit.

ok, but for the one-stage model, above bug is still exists. i wiil look forward to your solution to this problem. thanks for your answer and help.

**Comment by Jingkang50** [comment]
Noted. Thanks!

**Comment by Jingkang50** [comment]
Fixed
