### ISSUE TITLE
No checkpoint of `GPSNet` Baseline

### ISSUE THREAD

**Issue by ShunchiZhang** [Jingkang50/OpenPSG#15]
In `Model Zoo` section of `README.md`, it provides checkpoints of 5 baselines but none for `GPSNet`.

https://github.com/Jingkang50/OpenPSG/blob/f8e33fb297ba37eedaad39764060e3103b5d9ad3/README.md?plain=1#L223-L230

Not sure if the checkpoint of `GPSNet` was missed by accident or I didn't understand this table correctly.

Any responses would be appreciated. Thanks!

**Comment by Jingkang50** [comment]
Will be added together in our next update. Thank you for your comments!

**Comment by Jingkang50** [comment]
Actually, we considered this option before. 
But given that our school only gave us free storage quota on OneDrive, we did not find a good way to download files with code from OneDrive. 
Anyway, your suggestion is valid and we gonna keep this enhancement feature in mind.
