### ISSUE TITLE
a bug for train_psgformer?

### ISSUE THREAD

**Issue by ZHUXUHAN** [Jingkang50/OpenPSG#16]
File "/userhome/miniconda3/envs/psg/lib/python3.7/site-packages/mmdet/apis/train.py", line 158, in train_detector
    cfg.device,
  File "/userhome/miniconda3/envs/psg/lib/python3.7/site-packages/mmcv/utils/config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'device'

when i run the train_psgformer.sh of  the one-stage  psgformer model, i meet this problem.
how can i solve this problem?

**Comment by Jingkang50** [comment]
Sounds like a problem due to mmdet version. Have you tried to look for the solutions from mmdet, like https://github.com/open-mmlab/mmdetection/issues/7901

**Comment by ZHUXUHAN** [comment]
yep, my mmdet is mmdet-2.25.1, this version will meet this problem, so when i reinstall the mmdet-2.20.0, the problem is missed.
thansks.
