### ISSUE TITLE
Deduplicate Triplets for HuggingFace Demo

### ISSUE THREAD

**Issue by Jingkang50** [Jingkang50/OpenPSG#20]

**Comment by GSeanCDAT** [comment]
Done.

**Comment by Jingkang50** [comment]
@c-liangyu Hi Liangyu, could you help check and update the online demo?

**Comment by c-liangyu** [comment]
Our hugging face is on hugging_face_demo branch, which has resolved duplicate issue.
Probably we will PR, so dedup postprocessing can be used for other applications.
