### ISSUE TITLE
Could not write output to result.pkl by test.py

### ISSUE THREAD

**Issue by JarvisUSTC** [Jingkang50/OpenPSG#22]
Script:
  python tools/test.py configs/psgtr/psgtr_r50_psg.py work_dirs/checkpoints/PSGTR/epoch_psgtr_baseline.pth --out work_dirs/psgtr_r50_psg/result.pkl --eval sgdet

The log shows below:
  creating index...
  index created!
  load checkpoint from local path: work_dirs/checkpoints/PSGTR/epoch_psgtr_baseline.pth
  [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 2177/2177, 0.7 task/s, elapsed: 3003s, ETA:     0s
  writing results to work_dirs/psgtr_r50_psg/result.pkl
  Killed

I could not find the result.pkl in the path.

**Comment by Jingkang50** [comment]
Looks like the result.pkl exceed your memory, so it cannot be saved.
Usually, saving result.pkl is not necessary, so you can just run 
```
python tools/test.py configs/psgtr/psgtr_r50_psg.py work_dirs/checkpoints/PSGTR/epoch_psgtr_baseline.pth --eval sgdet
```

Or if you want to analyze result.pkl, you could uncomment [here](https://github.com/Jingkang50/OpenPSG/blob/23419d7c4b80a6bd986f0a74921647c4480c2dc1/openpsg/datasets/psg.py#L97) to make result file smaller.

**Comment by JarvisUSTC** [comment]
Thanks for your advice.

Because of the faster inference of PSGFormer, I run the PSGFormer test script to validate the hypothesis:
`python tools/test.py configs/psgformer/psgformer_r50_psg.py work_dirs/checkpoints/epoch_baseline.pth --eval sgdet
`
However, there exists another bug QWQ

```
creating index...
index created!
load checkpoint from local path: work_dirs/checkpoints/epoch_baseline.pth
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 2177/2177, 1.4 task/s, elapsed: 1581s, ETA:     0s
Loading testing groundtruth...

[>>>>>>>>>>>>>>>>>>>>>>                            ] 1000/2177, 78.6 task/s, elapsed: 13s, ETA:    15sTraceback (most recent call last):
  File "tools/test.py", line 244, in <module>
    main()
  File "tools/test.py", line 236, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/datadisk/v-jiaweiwang/OpenPSG/openpsg/datasets/psg.py", line 383, in evaluate
    rel_pair_idxes=ann['rels'][:, :2],
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by Jingkang50** [comment]
Did you use our latest codebase and the data provided by the [competition](https://www.cvmart.net/race/10349/base)?
The current codebase only supports the competition. Do you use 'psg_train_val.json'?

**Comment by JarvisUSTC** [comment]
I use 'psg_val_test.json', this is not for final evaluation?

**Comment by JarvisUSTC** [comment]
Oh, I know. The final evaluation should be done on the competition server.

**Comment by JarvisUSTC** [comment]
Thanks. By the way, I also meet the same bug when using "--submit" as before. 'NoneType' object has no attribute 'astype'

**Comment by JarvisUSTC** [comment]
I have already attained the validate evaluation result.
