### ISSUE TITLE
what is different of the pretrained model of psgtr and psgformer?

### ISSUE THREAD

**Issue by ZHUXUHAN** [Jingkang50/OpenPSG#24]
what is different of the pretrained model of psgtr and psgformer?  i think they  may be same as i see in your paper.
and how do you generate the pretrained model. just from the detr mdel trained on coco dataset?
or something?

**Comment by Jingkang50** [comment]
The pretrained models for PSGTR and PSGFormer are generally from coco pretrained DETR from mmdet. The only difference is that PSGFormer has two decoder, with relation decoder random initialized. We wrote a very simple script to covert checkpoint keys to get the pretrained checkpoints.

All pretrained models are provided, you could refer to readme and find it.

**Comment by ZHUXUHAN** [comment]
> The pretrained models for PSGTR and PSGFormer are generally from coco pretrained DETR from mmdet. The only difference is that PSGFormer has two decoder, with relation decoder random initialized. We wrote a very simple script to covert checkpoint keys to get the pretrained checkpoints.
> 
> All pretrained models are provided, you could refer to readme and find it.

Thank you very much for answering my confusion！

**Comment by ZHUXUHAN** [comment]
I'm sorry to bother you again, I haven't found a script for the conversion, can you provide it?

**Comment by Jingkang50** [comment]
@wzy27 could you help paste the key conversion code here?
@ZHUXUHAN FYI, we provided the pretrained model [here](https://entuedu-my.sharepoint.com/:f:/g/personal/jingkang001_e_ntu_edu_sg/ErQ4stbMxp1NqP8MF8YPFG8BG-mt5geOrrJfAkeitjzASw?e=9taAaU) in case you just wanna re-train PSGTR and PSGFormer. Or you are planning to train your own model with a similar pipeline?

**Comment by ZHUXUHAN** [comment]
In addition, I did not find a panoptic segmentation model similar to detr in mmdetection official. Did you train it from scratch?

**Comment by wzy27** [comment]
basically that's how we do the conversions:
`detr = torch.load('work_dirs/checkpoints/detr_r50_8x2_150e_coco_20201130_194835-2c4b8974.pth')
state_dict = detr['state_dict']

state_dict_keys = list(state_dict.keys())
for k in state_dict_keys:
    if 'bbox_head.transformer.decoder' in k:
        convert_key1 = k.replace('bbox_head.transformer.decoder', 
                                 'bbox_head.transformer.decoder1')
        state_dict[convert_key1] = state_dict[k]

        convert_key2 = k.replace('bbox_head.transformer.decoder', 
                                 'bbox_head.transformer.decoder2')
        state_dict[convert_key2] = state_dict[k]
        
        del state_dict[k]`

**Comment by Jingkang50** [comment]
> Yes, we want to retrain one. In addition, I did not find a panoptic segmentation model similar to detr in mmdetection official. Did you train it from scratch?

The DETR (for panseg) model checkpoints were from the [original detr repo](https://github.com/facebookresearch/detr#:~:text=COCO%20panoptic%20val5k%20models%3A). We did not trained the pretrained model.

**Comment by ZHUXUHAN** [comment]
> original detr repo
thanks for your answer！

**Comment by ZHUXUHAN** [comment]
> thanks for your answer！

thanks for your answer！

**Comment by ZHUXUHAN** [comment]
> basically that's how we do the conversions:
> 
> ```
> detr = torch.load('work_dirs/checkpoints/detr_r50_8x2_150e_coco_20201130_194835-2c4b8974.pth')
> state_dict = detr['state_dict']
> 
> state_dict_keys = list(state_dict.keys())
> for k in state_dict_keys:
>     if 'bbox_head.transformer.decoder' in k:
>         convert_key1 = k.replace('bbox_head.transformer.decoder', 
>                                  'bbox_head.transformer.decoder1')
>         state_dict[convert_key1] = state_dict[k]
> 
>         convert_key2 = k.replace('bbox_head.transformer.decoder', 
>                                  'bbox_head.transformer.decoder2')
>         state_dict[convert_key2] = state_dict[k]
>         
>         del state_dict[k]
> ```

thanks for your answer！
