### ISSUE TITLE
How to generate a SG for a single image using pretrained weights?

### ISSUE THREAD

**Issue by Chandu-4444** [Jingkang50/OpenPSG#32]
I'm trying to run inference on a single image (not necessarily from the dataset), but I couldn't find a way to do that. Can someone help me?

**Comment by Jingkang50** [comment]
Please check [`predict.py`](https://github.com/Jingkang50/OpenPSG/blob/main/predict.py)

**Comment by Chandu-4444** [comment]
I tried replicating that, but it killed my terminal at this line: `result = inference_detector(self.model, input_image)` due to OOM error. My system has 8GB ram.

**Comment by Chandu-4444** [comment]
> I tried replicating that, but it killed my terminal at this line: `result = inference_detector(self.model, input_image)` due to OOM error. My system has 8GB ram.

Can I run this on colab? I'm not sure if colab supports conda envs.

**Comment by c-liangyu** [comment]
The easiest way to infer one image is through our Hugging Face/Replicate demo, for which you can find links in our README.

Yes you can run on colab, below are some refereces.
[1] Check our source code for hugging face demo for single image inference on PSGTR.
https://huggingface.co/spaces/ECCV2022/PSG/blob/main/app.py
[2] Our code is based on mmdetection, you can check this notebook for installation and configuration.
https://colab.research.google.com/github/ZwwWayne/mmdetection/blob/update-colab/demo/MMDet_Tutorial.ipynb


Can you post the error message in this issue? Thank you.

**Comment by Chandu-4444** [comment]
```python
ModuleNotFoundError: No module named 'cog'

```

**Comment by Chandu-4444** [comment]
```bash
File "/content/drive/My Drive/BTP Work/OpenPSG/openpsg/utils/utils.py", line 323, in show_result
    rel_topk_idx = np.argpartition(rel_scores, -n_rel_topk)[-n_rel_topk:]
TypeError: bad operand type for unary -: 'FieldInfo'
```

**Comment by c-liangyu** [comment]
Please include the call stack in the error message for debugging.

**Comment by c-liangyu** [comment]
Can you check the data type of input_image? It should be a numpy array.

https://github.com/Jingkang50/OpenPSG/blob/main/predict.py#35
```python
input_image = mmcv.imread(str(image))
        result = inference_detector(self.model, input_image)
        out_path = Path(tempfile.mkdtemp()) / "output.png"
        out_dir = "temp"
        show_result(
            str(image),
            result,
            is_one_stage=True,
            num_rel=num_rel,
            out_dir=out_dir,
            out_file=str(out_path),
        )
```

**Comment by Chandu-4444** [comment]
> Can you check the data type of input_image? It should be a numpy array.
> 
> https://github.com/Jingkang50/OpenPSG/blob/main/predict.py#35
> 
> ```python
> input_image = mmcv.imread(str(image))
>         result = inference_detector(self.model, input_image)
>         out_path = Path(tempfile.mkdtemp()) / "output.png"
>         out_dir = "temp"
>         show_result(
>             str(image),
>             result,
>             is_one_stage=True,
>             num_rel=num_rel,
>             out_dir=out_dir,
>             out_file=str(out_path),
>         )
> ```

Oh yeah. Thanks! It seems like I'm using a corrupted image. It now works fine.
