### ISSUE TITLE
Results are zero when training the PSGFormer

### ISSUE THREAD

**Issue by hszhoushen** [Jingkang50/OpenPSG#33]
The problem is that results are always zero on the resnet50 and resnet101 backbone. What is the problem behind this phenomenon?

![image](https://user-images.githubusercontent.com/13336464/186362258-8440a0d0-3f47-45ab-b309-658565b67f75.png)

![image](https://user-images.githubusercontent.com/13336464/186362508-7f798586-4818-4f4e-a9b4-2c3be7ddfe3d.png)

**Comment by Jingkang50** [comment]
If you directly run our code without modification, maybe you did not load the pretrained model correctly.

**Comment by Jingkang50** [comment]
Here we attach the log file for psgformer: [20220713_165141.log](https://github.com/Jingkang50/OpenPSG/files/9414117/20220713_165141.log).
But notice that we use bbox-based IOU to compute recalls, which will produce a higher value than the default seg-based IOU recalls as we set [here](https://github.com/Jingkang50/OpenPSG/blob/main/configs/psgformer/psgformer_r50_psg.py#:~:text=detection_method%3D%27pan_seg%27%2C).

**Comment by hszhoushen** [comment]
Thanks for your information, however, it seems that the model is properly/successfully loaded.
![image](https://user-images.githubusercontent.com/13336464/186381920-eea58ac9-4b08-4764-864e-a442467d85a3.png)

**Comment by Jingkang50** [comment]
Not sure… Maybe pull the newest main and try to compare with the log file that we provided [20220713_165141.log](https://github.com/Jingkang50/OpenPSG/files/9414117/20220713_165141.log).

**Comment by iseekwonderful** [comment]
Could you please share the log file of PSGTR? I also face some difficulty in reproducing that.

**Comment by Jingkang50** [comment]
[20220704_001919.log](https://github.com/Jingkang50/OpenPSG/files/9423083/20220704_001919.log)
Thank you for asking. Similar to PSGFormer, this PSGTR log also uses `detection_method='bbox'` when evaluating, which yields a bit higher results than `detection_method='pan_seg'`.

**Comment by pingapplepen** [comment]
Hi @hszhoushen did you solve this issue? I also have the this zero issue

**Comment by Yassin-fan** [comment]
> 感谢您提供信息，但是，模型似乎已正确/成功加载。 ![图像](https://user-images.githubusercontent.com/13336464/186381920-eea58ac9-4b08-4764-864e-a442467d85a3.png)

Sorry to bother you， it seemd that i meet the same problem for loading the pretrained model, and the result continues to be zero. Did you fix the problem here?

**Comment by wymanCV** [comment]
> [20220704_001919.log](https://github.com/Jingkang50/OpenPSG/files/9423083/20220704_001919.log) Thank you for asking. Similar to PSGFormer, this PSGTR log also uses `detection_method='bbox'` when evaluating, which yields a bit higher results than `detection_method='pan_seg'`.

Dear authors, 

@Jingkang50 Thank you for your excellent work! I have a minor confusion about the convergence speed of PSGTR. The provided log file illustrates that the convergence speed of PSGTR is satisfactory, e.g., reaching 29.8 @R100 at 12 epochs. However, in the main paper, the 12 epochs performance of PSGTR is very low. Is there some difference between them?

Thank you so much!
