### ISSUE TITLE
about the pre-trained model of two-stage?

### ISSUE THREAD

**Issue by ZHUXUHAN** [Jingkang50/OpenPSG#35]
Hello. Is the pretrained model of the two-stage approach trained by you on the coco dataset? or is it from open source? And if so, can you provide a link to the original pretrained model?

**Comment by Jingkang50** [comment]
https://github.com/open-mmlab/mmdetection/tree/master/configs/panoptic_fpn

The pretrained model is from mmdet.

**Comment by ZHUXUHAN** [comment]
By the way, i find your project don't support multi-scale test when we test the relation sgdet? Have you ever tried it and it didn't work?

**Comment by Jingkang50** [comment]
We did not try it. We only provide some standard baselines and hope participants to explore it from various directions.

**Comment by ZHUXUHAN** [comment]
> We did not try it. We only provide some standard baselines and hope participants to explore it from various directions.

ok, thanks!

**Comment by Nora-Zhang98** [comment]
Hello, thanks for your excellent work. I am trying to re-implemented your work. I found the log files of PSGTR and PSGFormer, and could you please provide the log files of MOTIFS of VCTree(ResNet-101)? Thank you!
