### ISSUE TITLE
Can I use the downloaded dataset in my paper?

### ISSUE THREAD

**Issue by Mikeworld-git** [Jingkang50/OpenPSG#36]
Hi, thanks for your work.
I have a question.Can I use the downloaded dataset in my paper?
The dataset is downloaded from here
![image](https://user-images.githubusercontent.com/74859919/187064754-7f28780c-6ec9-4bbc-acc5-d83bbcce06da.png)

**Comment by Jingkang50** [comment]
Thank you for your question.
Yes, you can use the data for any academic usage.

**Comment by Mikeworld-git** [comment]
Thank you for your reply.
Thanks for such a nice dataset！
