### ISSUE TITLE
Can you provide the script file for IDMatcher in id_assigner? 

### ISSUE THREAD

**Issue by wyz-gitt** [Jingkang50/OpenPSG#37]
Can you provide the script file for IDMatcher in id_assigner?
 KeyError:\'IdMatcher is not in the bbox_assigner registry\'"'
I had this problem while changing my code, so want your IDMatcher file.
Thank you!

**Comment by Jingkang50** [comment]
Thanks for your question.
Do you mean this file?
https://github.com/Jingkang50/OpenPSG/blob/4bb2e9316c656e2f170db5de778682089b7aca0f/openpsg/models/relation_heads/approaches/matcher.py#L129

**Comment by wyz-gitt** [comment]
This is it, thank you so much!
