### ISSUE TITLE
o_label = labels[o_idx] IndexError: list index out of range

### ISSUE THREAD

**Issue by Mikeworld-git** [Jingkang50/OpenPSG#38]
Hi!
Thank you for your nice work. I try to run your code, when I run test.py for validation, I get an error:

**the code i run：**
`python ./tools/test.py configs/vctree/panoptic_fpn_r50_fpn_1x_sgdet_psg.py ./data/vctree_panoptic_fpn_r50_fpn_1x_sgdet_psg/vctree_panoptic_fpn_r50_fpn_1x_sgdet_psg/epoch_12.pth  --eval sgdet --show-dir ./data/show_dir`

**the error：**
File "./tools/test.py", line 232, in main
    args.show_score_thr)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/apis/test.py", line 57, in single_gpu_test
    score_thr=show_score_thr)
  File "/OpenPSG-main/openpsg/models/frameworks/sg_panoptic_fpn.py", line 969, in show_result
    o_label = labels[o_idx]
IndexError: list index out of range

Is there something wrong with my config file?

**Comment by Jingkang50** [comment]
Ah, we did not test the `--show-dir` option in the test script for a while... If you want to visualize some samples, you could use the visualization.py separately.
