### ISSUE TITLE
Results are nearly zero when training the PSGTR

### ISSUE THREAD

**Issue by myukzzz** [Jingkang50/OpenPSG#39]
Results are always nearly zero on the resnet50 backbone. What is the problem behind this phenomenon?

![image](https://user-images.githubusercontent.com/68174757/187647228-173c7ca5-18f7-468d-ba86-0d44ee3ecc72.png)

It seems that the model is properly/successfully loaded and I set the lr=0.0001 as the log you provided

![image](https://user-images.githubusercontent.com/68174757/187648013-67fdd68f-33dc-41f1-bfa2-caac2a1cc439.png)

![image](https://user-images.githubusercontent.com/68174757/187647755-cfeb3bad-157d-41c6-a347-b2c5aaa9a594.png)

**Comment by Jingkang50** [comment]
Maybe try some other lr? We train the code on 8 GPUs, you might need to tune the lr accordingly?

**Comment by myukzzz** [comment]
I have tried lr=1.25e-5 for a single gpu 
![image](https://user-images.githubusercontent.com/68174757/187650475-e0a7087c-c78c-41db-8e09-abf66ee3a2ba.png)
However, results are still nearly zero 
![image](https://user-images.githubusercontent.com/68174757/187650969-d4aa4350-9037-4d94-b3c7-566d6c422e75.png)

**Comment by Jingkang50** [comment]
How about join in our slack channel and ask other participants?

**Comment by myukzzz** [comment]
How to join in your slack channel? the  link on readme is no longer valid...

**Comment by Jingkang50** [comment]
Join me on Slack -- it’s a faster, simpler way to work. Sign up here, from any device: https://join.slack.com/t/psgdataset/shared_invite/zt-1f8wkjfky-~uikum1YA1giLGZphFZdAQ

**Comment by myukzzz** [comment]
Ok, I have join it. Thanks.

**Comment by pingapplepen** [comment]
@myukzzz Hi how did you solve the issue? I'm having the same issue, is it due to learning rate?

**Comment by llipa** [comment]
@Jingkang50 I'm facing the same issue... Is this issue solved now? May you share us how to deal with it.

**Comment by Jingkang50** [comment]
Yes, our code runs on 8 gpus. If you run on other number of gpus, you might need to change the lr accordingly. @myukzzz could you also help comment?

**Comment by llipa** [comment]
Thanks for your timely reply. I tried to set lr = 0.00001 and it works.
