### ISSUE TITLE
ERROR:root:Evaluation failed! The length of results is not equal to the dataset len: 1000 != 2177

### ISSUE THREAD

**Issue by LiangJunYu88** [Jingkang50/OpenPSG#42]
After running test.py --submit, I got panseg folder with only 1K png and one json file.When I submit in the competition , it reported an error.Here is the log.
[>>>>>>>>>> ] 816/2177, 74.1 task/s, elapsed: 11s, ETA: 18s
[>>>>>>>>>> ] 817/2177, 74.1 task/s, elapsed: 11s, ETA: 18s
[>>>>>>>>>> ] 818/2177, 74.2 task/s, elapsed: 11s, ETA: 18s
[>>>>>>>>>> /usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
out=out, **kwargs
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
ret = ret.dtype.type
ret / rcount
**ERROR:root:Evaluation failed! The length of results is not equal to the dataset len: 1000 != 2177**
INFO:root:Response data:{
"code": -1,
"message": "failure",
"id": "2267",
"data": {}
}
INFO:root:{
"code": -1,
"message": "failure",
"id": "2267",
"data": {}
}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection
1
: www.cvmart.net:443

**Comment by Jingkang50** [comment]
https://github.com/Jingkang50/OpenPSG#:~:text=Before%20October%202022%2C%20we%20only%20release%20part%20of%20the%20PSG%20data%20for%20competition%2C%20where%20part%20of%20the%20test%20set%20annotations%20are%20wiped%20out.%20Users%20should%20change%20the%20json%20filename%20in%20psg.py%20(Line%204%2D5)%20to%20a%20correct%20filename%20for%20training%20or%20submission.

**Comment by Jingkang50** [comment]
https://github.com/Jingkang50/OpenPSG/blob/23f9c89d43eeaa6e4ee57895d11ac9fb3546fd47/configs/_base_/datasets/psg.py#L5

**Comment by Jingkang50** [comment]
Thank you for your question. Please refer to the instruction in the readme, and use the code above for submission.

**Comment by LiangJunYu88** [comment]
Thank you for your reply.
