### ISSUE TITLE
KeyError: 'relations'

### ISSUE THREAD

**Issue by Shunta-Shimizu** [Jingkang50/OpenPSG#43]
Hello.
When I ran ./ ce7475/ main.py , I got the error message like this

file: ~/OpenPSG/ce7454/dataset.py", line 81, in  __getitem__ 
soft_label[sample['relations']] = 1
KeyError: 'relations'

How should I modify the code?

**Comment by Jingkang50** [comment]
I would recommend to use 'pdb' to debug on your own first. 
Looks like the problem is on your json file path, as I cannot tell more based on the clues you give.

**Comment by Shunta-Shimizu** [comment]
OK.
Thank you!
