### ISSUE TITLE
Field Definition of "psg_cls_advanced.json"

### ISSUE THREAD

**Issue by Elfsong** [Jingkang50/OpenPSG#54]
Hi,

Where can I find the definition of each field in the file "psg_cls_advanced.json"? For example:

- What do "category_id", "area", and "gqa_category_id" stand for in the "segments_info" section?
- How does the "relations" section work? There are multiple groups of "relations", so which objects does this depict the relations between?
- In the "annotations" part, what is "bbox_mode"? Is the definition of "category_id" the same as in the "segments_info" section?

In the "psg_cls_basic.json", do "relations" fields include **ALL** relationships between objects in an image?

An introduction to this kind of terminology and how these things work together will be very helpful to fresh CVers.

Best,
Mingzhe

**Comment by Jingkang50** [comment]
Thank you for your questions.
