### ISSUE TITLE
ERROR:root:Invalid Prediction dir:/home/data/prediction/submission for 

### ISSUE THREAD

**Issue by ZHUXUHAN** [Jingkang50/OpenPSG#57]
when submit our zip, the error occurs. how can we modify it?

**Comment by moshuilanting** [comment]
when I submit the result zip, it always return failure with:

Evaluating sgdet...
ERROR:root:Evaluation failed!
INFO:root:Response data:{
"code": -1,
"message": "failure",
"id": "4925",
"data": {}
}
INFO:root:{
"code": -1,
"message": "failure",
"id": "4925",
"data": {}
}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection

**Comment by Jingkang50** [comment]
I recommend you to contact the competition server admin via WeChat Group ([QR code](https://www.cvmart.net/race/10349/base#:~:text=5%EF%BC%89%E5%A4%A7%E8%B5%9B%E5%AE%98%E6%96%B9%E5%BE%AE%E4%BF%A1%E7%BE%A4%EF%BC%8C%E6%89%AB%E7%A0%81%E5%8A%A0%E5%85%A5%E7%A4%BE%E7%BE%A4%EF%BC%8C%E5%8F%8A%E6%97%B6%E8%8E%B7%E5%8F%96%E5%A4%A7%E8%B5%9B%E4%BF%A1%E6%81%AF)) to get more details.
