### ISSUE TITLE
Trouble downloading the dataset (identity number?)

### ISSUE THREAD

**Issue by tqandi** [Jingkang50/OpenPSG#59]
Hi, I tried downloading the dataset from the link provided in the readme file (cvmart.net), but after registering in the website, it still says that the dataset is only available after registering in the competition. To be able to register, a field that translates to "identity number" is required. Unfortunately I don't speak Chinese and the website is not available in any other language, and I'm not sure I know what kind of id is accepted.

**Comment by Jingkang50** [comment]
Thank you for your interest in the PSG dataset. 
Please refer to the instruction here to proceed. If you have more questions, you could use Slack or email me for more instruction.
https://github.com/Jingkang50/OpenPSG/blob/main/psg_challenge.md
