### ISSUE TITLE
The test results of the PSGTR model are incorrect

### ISSUE THREAD

**Issue by zishengzheqiang** [Jingkang50/OpenPSG#60]
I use the epoch_60.pth of PSGTR model to run test scripts
![1663815778256](https://user-images.githubusercontent.com/102336089/191649085-d463e385-de89-4ef2-85ca-d8ff27fee010.png)

I change the detection_method='bbox'
![1663815965952](https://user-images.githubusercontent.com/102336089/191649407-cd0f402c-0b4a-4fa9-8dab-a304dcb457e0.png)

This is the result in the log file you gave
![1663816185885](https://user-images.githubusercontent.com/102336089/191649853-38be18c3-5f8d-4a0b-a8a9-5bbee7935e5e.png)
There is a big difference between them，What is the problem behind this phenomenon?

**Comment by Jingkang50** [comment]
https://github.com/Jingkang50/OpenPSG/discussions/51
Thanks for your question. You might refer to this discussion.

**Comment by Jingkang50** [comment]
In short, you might need to change

OpenPSG/openpsg/models/frameworks/psgtr.py

Line 16 in a0e5c8f

def triplet2Result(triplets, use_mask, eval_pan_rels=True):

to eval_pan_rels=False.

**Comment by zishengzheqiang** [comment]
Thanks for your detailed explanation! I set eval_pan_rels=False and R@20 is higher than before.
But the competition needs to submit a panseg png file, we should set eval_pan_rels=True, so the R@20 is low, Is it possible to conclude that the one-stage algorithm is worse than the two-stage algorithm?

> In short, you might need to change
> 
> OpenPSG/openpsg/models/frameworks/psgtr.py
> 
> Line 16 in [a0e5c8f](https://github.com/Jingkang50/OpenPSG/commit/a0e5c8f92b7c27883c545ae5f684584a5fa8b351)
> 
> def triplet2Result(triplets, use_mask, eval_pan_rels=True):
> 
> to eval_pan_rels=False.

**Comment by zishengzheqiang** [comment]
I get it, thank you so much!
