### ISSUE TITLE
How to record the best results？

### ISSUE THREAD

**Issue by shuizaola** [Jingkang50/OpenPSG#61]
The test set and validation set in this experiment are the same, so after running 12 epochs, the checkpoints are saved as lastest.pth. Is the lastest.pth the best? If not, can the results record the best of the results validated after each epoch? If so how to save the best model instead of the last model?

**Comment by Jingkang50** [comment]
You can change the `checkpoint_config` to save more ckpts. https://github.com/Jingkang50/OpenPSG/blob/23f9c89d43eeaa6e4ee57895d11ac9fb3546fd47/configs/psgtr/psgtr_r50_psg.py#L215

**Comment by shuizaola** [comment]
> You can change the `checkpoint_config` to save more ckpts.
> 
> https://github.com/Jingkang50/OpenPSG/blob/23f9c89d43eeaa6e4ee57895d11ac9fb3546fd47/configs/psgtr/psgtr_r50_psg.py#L215
Thank you for your reply, then is the result in your paper the result of verification after the last epoch（the 12th epoch）, or the best result after each verification of 12 epochs?（I mean the 12th epoch is not necessarily the best result, the best result may be in the checkpoints saved after the 8th epoch, then I will record the result of the 8th checkpoints record）

**Comment by Jingkang50** [comment]
The lastest.pth is not necessarily the best. If you need the ckpt for the best result, you may need to save more ckpts by changing `max_keep_ckpts`. Usually the best result is among them.
