### ISSUE TITLE
[Error] 

### ISSUE THREAD

**Issue by MrWhiteHomeman** [Jingkang50/OpenPSG#73]
when I run test.py --submit,  i meet this error,  how to modify code， Wait for you reply!!!

[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 2177/2177, 6.7 task/s, elapsed: 323s, ETA:     0s
Loading testing groundtruth...

[>>>>>>>>>>>>>>>>>>>>>>                            ] 1000/2177, 185.4 task/s, elapsed: 5s, ETA:     6sTraceback (most recent call last):
  File "tools/test.py", line 245, in <module>
    main()
  File "tools/test.py", line 236, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/dahuafs/userdata/46623/PSG/OpenPSG-main/openpsg/datasets/psg.py", line 388, in evaluate
    rel_pair_idxes=ann['rels'][:, :2],
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by Jingkang50** [comment]
Please check this
https://github.com/Jingkang50/OpenPSG/blob/ae418a15f6c0d558b665ffaca3ec0dd52e0f6f24/openpsg/datasets/psg.py#L79
