### ISSUE TITLE
The Code with mmcv is hard to understand.

### ISSUE THREAD

**Issue by BJHYZJ** [Jingkang50/OpenPSG#74]
Hello, dear authors. Thank you for your contribution to the field of scene graph generation, I find your work very interesting, but when I was about to reproduce your article or wish to follow your work, I was very uncomfortable with the opaqueness of the mmcv framework and could not modify the code properly, so I would like to ask if you could provide a pure pytorch version of the code or provide us with some reference materials for learning mmcv, I would appreciate it.

**Comment by Jingkang50** [comment]
Thanks for the question.
The PSG task contains important components from detection and segmentation, which is not easy to be implemented by pure pytorch. MMdet is one of the best detection framework, which would make the code easier. If you want to dive deep in PSG and dense prediction tasks, I believe you should be familiar with the framework.
You can use "debug" mode in vscode to explore the mmdet and mmcv frameworks.
Good luck!
