### ISSUE TITLE
Reduce the dataset for model training

### ISSUE THREAD

**Issue by Mikeworld-git** [Jingkang50/OpenPSG#77]
Hello，Thank you for your great work.
Due to the limitation of computer performance, I want to reduce the dataset for model training.Therefore, I changed the name of "psg_val_test. json" to "psg_train_val. json" to replace training, but the dataset could not be loaded correctly. What is the problem with the settings.

**Comment by 1154985402** [comment]
i ask for this author and get this tiny_psg.json file in jyputer. it may help you. 

[https://entuedu-my.sharepoint.com/personal/jingkang001_e_ntu_edu_sg/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fjingkang001%5Fe%5Fntu%5Fedu%5Fsg%2FDocuments%2Fopenpsg%2Fdata&ga=1](url)
