### ISSUE TITLE
Questions about annotations of test data

### ISSUE THREAD

**Issue by Coco-wyc** [Jingkang50/OpenPSG#80]
Hi, I noticed that the full datasets are released in 2022/10/31.

However, in file **psg_val_test.json**, there are 2177 images in test data but only 1000 images have the 'relations' label (1000 images for validation). How can we acquire the labels of the other 1177 test images?

**Comment by Coco-wyc** [comment]
I have found them in psg.json!

**Comment by Mikeworld-git** [comment]
> I have found them in psg.json!

Hi,i download full datases and use "psg_val_test.json" for test.but i meet the same problem. 
![image](https://user-images.githubusercontent.com/74859919/203926238-201be599-c239-4d37-bbde-a8c91163cf36.png)


Could you tell me how to solve it
