### ISSUE TITLE
Error running the test for configs/psgtr/psgtr_r50_psg.py 

### ISSUE THREAD

**Issue by Chandu-4444** [Jingkang50/OpenPSG#83]
I tried to run the following on (tiny_psg.json dataset):

```python
(/home/openpsg_env) root@c6747fffa95c:/home/BTP/OpenPSG# python tools/test.py --config configs/psgtr/psgtr_r50_psg.py --checkpoint epoch_60_psgr.pth --eval sgdet
```

I ran into the following error:

```python
load checkpoint from local path: epoch_60_psgr.pth
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 2186/2186, 3.2 task/s, elapsed: 678s, ETA:     0s
Loading testing groundtruth...

[>>>>>                                             ] 231/2186, 121.5 task/s, elapsed: 2s, ETA:    16sTraceback (most recent call last):
  File "tools/test.py", line 245, in <module>
    main()
  File "tools/test.py", line 237, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/home/openpsg_env/lib/python3.7/site-packages/cog-0.0.1-py3.7.egg/openpsg/datasets/psg.py", line 383, in evaluate
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by Mikeworld-git** [comment]
Hi，i meet the same problem。Have you solved the problem

**Comment by Chandu-4444** [comment]
Nope. I'm still trying.

**Comment by Mikeworld-git** [comment]
> Nope. I'm still trying.

I download full datases and use "psg_val_test.json" for test.but i meet the same problem.
![image](https://user-images.githubusercontent.com/74859919/203928038-89d2fd24-4a89-41ab-a7c0-530ad1ab75bf.png)

**Comment by Mikeworld-git** [comment]
> 



> Sorry, I was on vacation in the past few days. You could check [this part](https://github.com/Jingkang50/OpenPSG/blob/ae418a15f6c0d558b665ffaca3ec0dd52e0f6f24/openpsg/datasets/psg.py#L79). Also, please use our full-released dataset in the README News.

Thanks,i will try this way!
