### ISSUE TITLE
IndexError: too many indices for tensor of dimension 1

### ISSUE THREAD

**Issue by Fillip1233** [Jingkang50/OpenPSG#85]
Hi,authors.Thank you for your excellent work of open source. When I was training with a complete dataset, I encountered the following problems. Did I miss any details?
<img width="477" alt="image" src="https://user-images.githubusercontent.com/89203680/204996522-5b459019-a7dd-4c3a-a16a-f47c152faaca.png">

**Comment by Jingkang50** [comment]
Did you check [this part](https://github.com/Jingkang50/OpenPSG/blob/ae418a15f6c0d558b665ffaca3ec0dd52e0f6f24/openpsg/datasets/psg.py#L79)?

**Comment by Fillip1233** [comment]
Thank you for your quick reply!I have modified this file, but the error result is still the same.

**Comment by Jingkang50** [comment]
Not quite so sure. I suppose the problem is that some images do not have relation, so with the following code could solve the problem. Could you help check again, or find the image that causes the error.
``` 
        dataset['data'] = [
            d for d in dataset['data'] if len(d['relations']) != 0
        ]
```

**Comment by Fillip1233** [comment]
Thanks again for your quick reply!The problem is as you said,when I restart debug mode, the program can run normally.Thank you!
