### ISSUE TITLE
Problem about  using multiple GPUs for one-stage methods

### ISSUE THREAD

**Issue by Fillip1233** [Jingkang50/OpenPSG#86]
Hi,author!I encountered a problem when using multi gpu training.If I want to specify the gpu card number for training, how should I set it?I can't seem to find a solution.In addition, the multi gpu training instructions you provide on readme use distributed training. Is the -- gpus 8 parameter configuration ineffective? thank you!

**Comment by Fillip1233** [comment]
I'm sorry I ignored some information. I've solved the problem. Thank you

**Comment by Hanzy1996** [comment]
I have the same question. Could you please share how you solve it?

Best Regards.
