### ISSUE TITLE
I set "with_visual_mask = True" , But  the error 

### ISSUE THREAD

**Issue by wyz-gitt** [Jingkang50/OpenPSG#88]
There is no "ShapeAwareRoIAlign" class in the code. Can you provide the code of this class?
I set  the mask_roi_layer=dict(type='ShapeAwareRoIAlign',output_size=7,sampling_ratio=2),  "openpsg/models/roi_extractors/visual_spatial.py  in line 270 and 274,
270:
if roi_layers[i].__class__.__name__ == 'ShapeAwareRoIAlign':
274:
     roi_feats_t = roi_layers[i](feats[i], rois_, masks_)  :
At this time, "ShapeAwareRoIAlign" will be used to extract features, but the class "ShapeAwareRoIAlign" cannot be found. Can you provide the code for "ShapeAwareRoIAlign"?

**Comment by Jingkang50** [comment]
https://github.com/Jingkang50/OpenPSG/issues/8
