### ISSUE TITLE
About table result 

### ISSUE THREAD

**Issue by sirosann** [Jingkang50/OpenPSG#89]
Hello
I have a issues about a description in the paper.
After table 2 writed
[ For example, even the most classic method IMP can reach over 30% R@20, which already exceeds all the available R@20 under the scene graph generation (SGDet) task (cf . 28.4% by PSGTR). ]
I wonder why the IMP predicate classification results are compared to PSGTR SSG results here.

thank you

**Comment by Jingkang50** [comment]
Thank you for the question. Compared to SGDet, SGCls is simpler since GT masks are provided.
(IMP's SGDet << PSGTR's SGDet) but (IMP's SGCls > PSGTR SGDet) show the accurate masks in the first stage might be important to get a high final SGDet score.

**Comment by sirosann** [comment]
Thank you for your answer.
I got it .
